on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      log_level:
        required: true
        type: string

env:
  TERRAFORM_VERSION: 1.7.4

jobs:
  release:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Terraform state
        uses: andreasisnes/organization-management/actions/terraform-init@main
        with:
          working_directory: ./Infrastructure
          environment: ${{ inputs.environment }}
          arm_client_id: ${{ vars.ARM_CLIENT_ID }}

      - name: Deploy Terraform
        uses: andreasisnes/organization-management/actions/terraform-init@main
        with:
          working_directory: ./Infrastructure
          arm_client_id: ${{ vars.ARM_CLIENT_ID }}
          arm_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          tf_args: -var environment="${{ inputs.environment }}
