on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      log_level:
        required: true
        type: string

env:
  TERRAFORM_VERSION: 1.7.4

jobs:
  release:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: kake
        uses: andreasisnes/organization-management/actions/terraform-init@v2
        with:
          working_dir: Infrastructure

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Set Logger
        run: |
          export TF_LOG="${{ inputs.log_level }}"

      - name: Terraform Apply
        working-directory: Infrastructure
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          terraform apply -auto-approve \
            -var environment="${{ inputs.environment }}" \
